
// This file has been generated by the GUI designer. Do not modify.
namespace hotelmanagementsystem.lazurniy.housekeeping
{
	public partial class PrintWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView PrintText;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button ExitPrint;

		private global::Gtk.Button PrintButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget hotelmanagementsystem.lazurniy.housekeeping.PrintWindow
			this.Name = "hotelmanagementsystem.lazurniy.housekeeping.PrintWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PrintWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hotelmanagementsystem.lazurniy.housekeeping.PrintWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.PrintText = new global::Gtk.TextView();
			this.PrintText.CanFocus = true;
			this.PrintText.Name = "PrintText";
			this.PrintText.Editable = false;
			this.PrintText.PixelsAboveLines = 3;
			this.PrintText.PixelsBelowLines = 3;
			this.PrintText.LeftMargin = 30;
			this.PrintText.RightMargin = 30;
			this.PrintText.Indent = 5;
			this.GtkScrolledWindow.Add(this.PrintText);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ExitPrint = new global::Gtk.Button();
			this.ExitPrint.CanFocus = true;
			this.ExitPrint.Name = "ExitPrint";
			this.ExitPrint.UseUnderline = true;
			this.ExitPrint.Label = global::Mono.Unix.Catalog.GetString("Отмена");
			this.hbox1.Add(this.ExitPrint);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ExitPrint]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.PrintButton = new global::Gtk.Button();
			this.PrintButton.CanFocus = true;
			this.PrintButton.Name = "PrintButton";
			this.PrintButton.UseUnderline = true;
			this.PrintButton.Label = global::Mono.Unix.Catalog.GetString("Открыть файл для печати");
			this.hbox1.Add(this.PrintButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.PrintButton]));
			w4.Position = 1;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 605;
			this.DefaultHeight = 605;
			this.Show();
			this.ExitPrint.Clicked += new global::System.EventHandler(this.OnCancelClicked);
			this.PrintButton.Clicked += new global::System.EventHandler(this.OnPreviewClicked);
		}
	}
}
